#!/bin/bash

echo "I: extra pre-processing for Chichewa to fix filenames."

mv 01_Genesis	GEN;	rename 's/01_Genesis/GEN/' GEN/*.wav;
mv 02_Exodus	EXO;	rename 's/02_Exodus/EXO/' EXO/*.wav;
mv 03_Leviticus	LEV;	rename 's/03_Leviticus/LEV/' LEV/*.wav;
mv 04_Numbers	NUM;	rename 's/04_Numbers/NUM/' NUM/*.wav;
mv 05_Deuteronomy	DEU;	rename 's/05_Deuteronomy/DEU/' DEU/*.wav;
mv 06_Joshua	JOS;	rename 's/06_Joshua/JOS/' JOS/*.wav;
mv 07_Judges	JDG;	rename 's/07_Judges/JDG/' JDG/*.wav;
mv 08_Ruth	RUT;	rename 's/08_Ruth/RUT/' RUT/*.wav;
mv 09_1\ Samuel	1SA;	rename 's/09_1\ Samuel/1SA/' 1SA/*.wav;
mv 10_2\ Samuel	2SA;	rename 's/10_2\ Samuel/2SA/' 2SA/*.wav;
mv 11_1\ Kings	1KI;	rename 's/11_1\ Kings/1KI/' 1KI/*.wav;
mv 12_2\ Kings	2KI;	rename 's/12_2\ Kings/2KI/' 2KI/*.wav;
mv 13_1\ Chronicles	1CH;	rename 's/13_1\ Chronicles/1CH/' 1CH/*.wav;
mv 14_2\ Chronicles	2CH;	rename 's/14_2\ Chronicles/2CH/' 2CH/*.wav;
mv 15_Ezra	EZR;	rename 's/15_Ezra/EZR/' EZR/*.wav;
mv 16_Nehemiah	NEH;	rename 's/16_Nehemiah/NEH/' NEH/*.wav;
mv 17_Esther	EST;	rename 's/17_Esther/EST/' EST/*.wav;
mv 18_Job	JOB;	rename 's/18_Job/JOB/' JOB/*.wav;
mv 19_Psalms	PSA;	rename 's/19_Psalms/PSA/' PSA/*.wav;
mv 20_Proverbs	PRO;	rename 's/20_Proverbs/PRO/' PRO/*.wav;
mv 21_Ecclesiastes	ECC;	rename 's/21_Ecclesiastes/ECC/' ECC/*.wav;
mv 22_Song\ Of\ Songs	SOS;	rename 's/22_Song\ Of\ Songs/SOS/' SOS/*.wav;
mv 23_Isaiah	ISA;	rename 's/23_Isaiah/ISA/' ISA/*.wav;
mv 24_Jeremiah	JER;	rename 's/24_Jeremiah/JER/' JER/*.wav;
mv 25_Lamentations	LAM;	rename 's/25_Lamentations/LAM/' LAM/*.wav;
mv 26_Ezekiel	EZK;	rename 's/26_Ezekiel/EZK/' EZE/*.wav;
mv 27_Daniel	DAN;	rename 's/27_Daniel/DAN/' DAN/*.wav;
mv 28_Hosea	HOS;	rename 's/28_Hosea/HOS/' HOS/*.wav;
mv 29_Joel	JOL;	rename 's/29_Joel/JOL/' JOL/*.wav;
mv 30_Amos	AMO;	rename 's/30_Amos/AMO/' AMO/*.wav;
mv 31_Obadiah	OBA;	rename 's/31_Obadiah/OBA/' OBA/*.wav;
mv 32_Jonah	JON;	rename 's/32_Jonah/JON/' JON/*.wav;
mv 33_Micah	MIC;	rename 's/33_Micah/MIC/' MIC/*.wav;
mv 34_Nahum	NAH;	rename 's/34_Nahum/NAH/' NAH/*.wav;
mv 35_Habakkuk	HAB;	rename 's/35_Habakkuk/HAB/' HAB/*.wav;
mv 36_Zephaniah	ZEP;	rename 's/36_Zephaniah/ZEP/' ZEP/*.wav;
mv 37_Haggai	HAG;	rename 's/37_Haggai/HAG/' HAG/*.wav;
mv 38_Zechariah	ZEC;	rename 's/38_Zechariah/ZEC/' ZEC/*.wav;
mv 39_Malachi	MAL;	rename 's/39_Malachi/MAL/' MAL/*.wav;
mv 40_Matthew	MAT;	rename 's/40_Matthew/MAT/' MAT/*.wav;
mv 41_Mark	MRK;	rename 's/41_Mark/MRK/' MRK/*.wav;
mv 42_Luke	LUK;	rename 's/42_Luke/LUK/' LUK/*.wav;
mv 43_John	JHN;	rename 's/43_John/JHN/' JHN/*.wav;
mv 44_Acts	ACT;	rename 's/44_Acts/ACT/' ACT/*.wav;
mv 45_Romans	ROM;	rename 's/45_Romans/ROM/' ROM/*.wav;
mv 46_1\ Corinthians	1CO;	rename 's/46_1\ Corinthians/1CO/' 1CO/*.wav;
mv 47_2\ Corinthians	2CO;	rename 's/47_2\ Corinthians/2CO/' 2CO/*.wav;
mv 48_Galatians	GAL;	rename 's/48_Galatians/GAL/' GAL/*.wav;
mv 49_Ephesians	EPH;	rename 's/49_Ephesians/EPH/' EPH/*.wav;
mv 50_Philippians	PHP;	rename 's/50_Philippians/PHP/' PHP/*.wav;
mv 51_Colossians	COL;	rename 's/51_Colossians/COL/' COL/*.wav;
mv 52_1\ Thessalonians	1TH;	rename 's/52_1\ Thessalonians/1TH/' 1TH/*.wav;
mv 53_2\ Thessalonians	2TH;	rename 's/53_2\ Thessalonians/2TH/' 2TH/*.wav;
mv 54_1\ Timothy	1TI;	rename 's/54_1\ Timothy/1TI/' 1TI/*.wav;
mv 55_2\ Timothy	2TI;	rename 's/55_2\ Timothy/2TI/' 2TI/*.wav;
mv 56_Titus	TIT;	rename 's/56_Titus/TIT/' TIT/*.wav;
mv 57_Philemon	PHM;	rename 's/57_Philemon/PHM/' PHM/*.wav;
mv 58_Hebrews	HEB;	rename 's/58_Hebrews/HEB/' HEB/*.wav;
mv 59_James	JAS;	rename 's/59_James/JAS/' JAS/*.wav;
mv 60_1\ Peter	1PE;	rename 's/60_1\ Peter/1PE/' 1PE/*.wav;
mv 61_2\ Peter	2PE;	rename 's/61_2\ Peter/2PE/' 2PE/*.wav;
mv 62_1\ John	1JN;	rename 's/62_1\ John/1JN/' 1JN/*.wav;
mv 63_2\ John	2JN;	rename 's/63_2\ John/2JN/' 2JN/*.wav;
mv 64_3\ John	3JN;	rename 's/64_3\ John/3JN/' 3JN/*.wav;
mv 65_Jude	JUD;	rename 's/65_Jude/JUD/' JUD/*.wav;
mv 66_Revelation	REV;	rename 's/66_Revelation/REV/' REV/*.wav;
rename 's/ /_/' */*.wav;
rename 's/_V[0-9]//' */*.wav;
rename 's/ //' PSA/PSA_122\ .wav
rename 's/_0+/_/' */*.wav
